---
- name: Install nginx
  yum: name=nginx state=present

- name: Remove default config
  file: name=/etc/nginx/conf.d/default.conf state=absent
  notify: Restart Nginx

- name: Start and enable nginx
  service: name=nginx enabled=yes state=started
